version: '3'

services:
  server:
    build:
      context: nginx
    container_name: server
    ports:
      - "8080:80"
    networks:
      - nodeapp_network
    depends_on:
      - app
  app:
    build:
      context: app
    container_name: nodeapp
    networks:
      - nodeapp_network
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodeapp_network

networks:
  nodeapp_network: